# Generated by Django 4.1.1 on 2022-10-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0002_message_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
