# Generated by Django 4.1.1 on 2022-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVapp', '0005_remove_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='cool cool'),
            preserve_default=False,
        ),
    ]
